version: '3'

services:
  db:
    image: store_db
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: store_app_db
      POSTGRES_USER: store_app
      POSTGRES_PASSWORD: store_app
    volumes:
      - store_db:/var/lib/postgresql/data
    networks:
      - store_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U store_app -d store_app_db"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    image: store_back
    container_name: backend
    ports:
      - 8000:8000
    environment:
      HOST: database
      PORT: 5432
      DB: store_app_db
      DB_USERNAME: store_app
      DB_PASSWORD: store_app
    volumes:
      - ../app:/store/app
    networks:
      - store_net
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8000/test"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  store_db:
    name: store_db

networks:
  store_net:
    name: store_net
